/follower/apriltag/apriltag:
  ros__parameters:
    image_transport: raw
    family: 36h11
    size: 0.050
    max_hamming: 0

    detector:
      threads: 4
      decimate: 1.0
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: false

    pose_estimation_method: "pnp"
    tag:
      ids: [0, 1, 2]
      frames:
        - "follower/tag36h11:0"
        - "follower/tag36h11:1"
        - "follower/tag36h11:2"
      sizes: [0.050, 0.050, 0.050]
