#include "variable.h"
#include <string.h>

sen_t g_sen[16];
race_info search_info[256];
fast_run_str g_fast_info[256];
error_str g_err;
position_t g_pos;
turnmark_t g_lmark;
turnmark_t g_rmark;
bit_field_flag_t g_Flag;
volatile uint32_t g_u32_isr_cnt;
volatile uint32_t g_u32_adc_error_cnt;
volatile uint32_t g_u32_motor_isr_cnt;
volatile int32_t g_i32_timer_cnt;
volatile int32_t g_i32_mark_cnt;
volatile int32_t g_i32_total_cnt;
volatile int32_t g_i32_err_cnt;
volatile int32_t g_i32_speed_up_cnt;
volatile uint16_t g_u16_pos_cnt;
volatile uint16_t g_u16_sen_enable;
volatile uint16_t g_u16_sen_state;
volatile uint16_t g_u16_turnmark_cnt;
volatile uint16_t g_u16_turn_dist;
volatile uint16_t g_u16_turnmark_limit;
volatile float g_fp32_user_vel;
volatile float g_fp32_user_acc;
volatile float g_fp32_end_vel;
volatile float g_fp32_end_acc;
volatile float g_fp32_endturn_acc;
volatile float g_fp32_fast_vel_limit;
volatile float g_fp32_straight_dist;
volatile float g_fp32_turn_angle;
volatile float g_fp32_current_angle;
volatile float g_fp32_gyro_dps_z;
volatile float g_fp32_gyro_tick_z;
volatile float g_fp32_sensor_value_max;
volatile float g_fp32_turnmark_dist;
volatile float g_fp32_straight_mark_dist;
volatile float g_fp32_mark_dist;
volatile float g_fp32_turn_threshold;
volatile float g_fp32_out_corner_limit;
volatile float g_fp32_in_corner_limit;
volatile float g_fp32_out_corner_fast_limit;
volatile float g_fp32_in_corner_fast_limit;
volatile float g_fp32_motor_kp;
volatile float g_fp32_motor_kd;
volatile int32_t g_i32_decel;
volatile int32_t g_i32_fast_error_flag;
volatile float g_fp32_left_handle;
volatile float g_fp32_right_handle;
volatile float g_fp32_handle_dec_max;
volatile float g_fp32_handle_acc_max;
volatile float g_fp32_handle_dec_step;
volatile float g_fp32_handle_acc_step;
volatile float g_fp32_left_handle_temp;
volatile float g_fp32_right_handle_temp;

void Variable_Init(void)
{
    memset((void *)g_sen, 0, sizeof(g_sen));
    memset((void *)search_info, 0, sizeof(search_info));
    memset((void *)g_fast_info, 0, sizeof(g_fast_info));
    memset((void *)&g_err, 0, sizeof(g_err));
    memset((void *)&g_pos, 0, sizeof(g_pos));
    memset((void *)&g_lmark, 0, sizeof(g_lmark));
    memset((void *)&g_rmark, 0, sizeof(g_rmark));
    memset((void *)&g_Flag, 0, sizeof(g_Flag));

    g_u32_isr_cnt = 0U;
    g_u32_adc_error_cnt = 0U;
    g_u32_motor_isr_cnt = 0U;
    g_i32_timer_cnt = 0;
    g_i32_mark_cnt = 0;
    g_i32_total_cnt = 0;
    g_i32_err_cnt = 0;
    g_i32_speed_up_cnt = 0;
    g_u16_pos_cnt = 6U;
    g_u16_sen_enable = 0U;
    g_u16_sen_state = 0U;
    g_u16_turnmark_cnt = 0U;
    g_u16_turn_dist = 73U;
    g_u16_turnmark_limit = 100U;
    g_fp32_user_vel = 2300.0f;
    g_fp32_user_acc = 13000.0f;
    g_fp32_end_vel = 2200.0f;
    g_fp32_end_acc = 12500.0f;
    g_fp32_endturn_acc = g_fp32_user_acc;
    g_fp32_fast_vel_limit = 7700.0f;
    g_fp32_straight_dist = 0.0f;
    g_fp32_turn_angle = 0.0f;
    g_fp32_current_angle = 0.0f;
    g_fp32_gyro_dps_z = 0.0f;
    g_fp32_gyro_tick_z = 0.0f;
    g_fp32_sensor_value_max = 50.0f;
    g_fp32_turnmark_dist = 70.0f;
    g_fp32_straight_mark_dist = g_fp32_turnmark_dist + 80.0f;
    g_fp32_mark_dist = g_fp32_turnmark_dist;
    g_fp32_turn_threshold = 60.0f;
    g_fp32_out_corner_limit = 0.400f;
    g_fp32_in_corner_limit = 2.600f;
    g_fp32_out_corner_fast_limit = 0.400f;
    g_fp32_in_corner_fast_limit = 2.600f;
    g_fp32_motor_kp = 0.42f;
    g_fp32_motor_kd = 0.62f;
    g_i32_decel = 15000;
    g_i32_fast_error_flag = 1;
    g_fp32_left_handle = 1.0f;
    g_fp32_right_handle = 1.0f;
    g_fp32_handle_dec_max = 0.0f;
    g_fp32_handle_acc_max = 0.0f;
    g_fp32_handle_dec_step = 0.0f;
    g_fp32_handle_acc_step = 0.0f;
    g_fp32_left_handle_temp = 1.0f;
    g_fp32_right_handle_temp = 1.0f;
    g_pos.u16_current_state = 0x0001U;
    g_pos.u16_past_state = 0x0001U;
}
