/leader/apriltag/apriltag:
  ros__parameters:
    image_transport: raw
    family: 36h11
    size: 0.050
    max_hamming: 0
    qos_profile: sensor_data
    detector:
      threads: 4
      decimate: 1.0
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: false
    pose_estimation_method: pnp
    tag:
      ids: [0]
      frames: ["tag36h11:0"]
      sizes: [0.050]
